#+TITLE: Seminar Report
#+AUTHOR: Martin Fracker
#+OPTIONS: toc:nil num:nil
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
* Summary
The seminar was about being successful in the career fair, how to look good on
one's resume, and how to impress talent officers by following up with them. The
most important things to remember when going to the career fair are presenting
oneself professionally and managing one's time wisely. First impressions are
everything when it comes to meeting recruiters, and one would want to meet as
many recruiters as possible to have the best chance at landing a good
interview. Making a good first impression requires appropriate dress and
demonstrating interest in the companies one inquires about. Sometimes recruiters
will accept a resume. One should have several resumes on hand for these types of
recruiters. There are several opportunities to get one's resume reviewed before
going to the career fair, either by appointment or walk-in. The resume is great
for giving the recruiter something to hang onto after the initial encounter, but
one can greatly increase his or her chances at an interview by shooting a 'thank
you' email afterwards and by periodically following up with recruiters until one
receives a response. Ultimately, the goal is to leave a good impression and then
maintain that impression.
* Thoughts
I had heard this lecture before, but as you would expect, I still managed to be
surprised and learn something new. One of the topics that surprised me like this
was about things to talk about at the career fair. Everyone is familiar with the
question that some recruiters ask: "Where do you see yourself 5-10 years from
now". Well it turns out there is a related question that the prospective
employee can ask: "Where can I expect this position to take my career?". It is
such an obvious question, but does anyone every think to ask it? There must be
so many ways to draw yourself in a positive light during an interview that may
not be so obvious as doing research on the company. Clearly, a lot goes into
preparing for a successful interview. Thinking creatively may go a long way in
having a successful one.
