#+TITLE: Seminar Report 8
#+AUTHOR: Martin Fracker
#+OPTIONS: toc:nil num:nil
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
* Summary
This seminar was about managing one's career growth. The speaker began with
several examples of famous people whose careers took unexpected turns to
demonstrate that careers are impacted by external events, sometimes random and
out of our control but also admitted that some events can be controlled and
many can be influenced. In order to manage career growth, you must know where
you want your career to go, continue to perform above your employer's
expectations, and keep your personal life in a balance with your career. You
must have some idea of where you want to be in 5 to 10 years. This is especially
important because employer's expectations are steadily rising, and if you cannot
meet your employer's expectations while nudging your career where you want it to
go you will either be laid off or wind up getting off track. It is important to
note that meeting your employer's expectations is not enough in the long term;
one must consistently exceed his or her employer's expectations. Be careful,
however, not to get so involved with your career that you either get burned out
or forget to devote time to other things such as your health, family, and
friends. It is important to be mature enough to recognize when you need to spend
time on other things besides your career. In some cases, you may be able to
recognize that you cannot advance any further in your career by doing the same
job or staying with the same company.
* Thoughts
The way the speaker began the lecture, that is by talking about his personal
life including his spiritual and love life, connected really well with his point
about cautioning yourself against focusing so much on your career that you
forget to spend time on your health, and with your family and friends. I think
that this can be applied even while in college. Working hard in school is
definitely a good thing. There are many things to be gained by working hard such
as a good work ethic and a sound internalization of knowledge. However, there
are so many other things to be gained in college that you won't gain while
working hard on your academics: sound social skills, a healthy lifestyle, and a
strong network.
