#+TITLE: Seminar Report 13
#+AUTHOR: Martin Fracker
#+OPTIONS: toc:nil num:nil
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
* Summary
The lecture today was about the legal and ethical issues in computer science,
information technology, and software engineering. In our careers, we will
inevitably come across difficult decisions. Sometimes the laws are clear-cut,
but most of the time we find ourselves in gray situations, and we need an
ethical framework that we can fallback on when the law does not make it clear
which decision is correct in terms of the issues of intellectual property.

The frameworks discussed included the utilitarian framework as well as moral
principles as a framework. In the utilitarian framework, the pros and cons are
enumerated, and the cost-risk analysis is taken into consideration to make a
decision, almost like an equation, something many engineers are familiar and
even comfortable with. Cost analysis is very attractive in this regard, however
in the past many terrible decisions have been made using this framework. One
alternative framework is moral principles. The most important aspect of moral
principles is that the reasons behind our actions matter just as much as the
outcome.

Many decisions in our career will revolve around Intellectual Property (IP). IP
includes patents, copyrights, trademarks, and trade secrets which all exist to
either encourage technological growth or protect works of authorship. Patents
usually encompass design and utility concepts: expressions of ideas. Copyrights
are typically associated with literature, music, works of art, and computer
software, and do not protect ideas. Furthermore, while software can be
copyrighted, algorithms cannot be copyrighted, nor patented; however, the
implementation thereof can by copyrighted. Software is unique in this regard:
source code appears to be an expression of an idea, while the object code is
seen as more of a utility.
* Thoughts
I managed to secure an internship this summer as a Rentsys Disaster Recovery
Intern where I will be troubleshooting a wide variety of software and hardware
as well as documenting everything along the way. This job will be one of my
first real-world opportunities to employ everything I have learned about ethics
in the workplace. I have not yet taken Engineering Ethics, but I have taken
Technical Business Writing which had an ethics component. Ethics are clearly
important because decision-making in the workplace tends to get
complicated. This is because not only does the law not cover everything but
also, especially for me, since I have not been in a real-world situation where
my ethical thinking has been truly exercised. After my internship this summer,
hopefully I will not only have some wholesome exercise making tough decisions
but I will also feel more confident in making those decisions in the future.
